### ISSUE TITLE
2020q3/graphics.md

### ISSUE THREAD

**Issue by pauamma** [freebsd/freebsd-quarterly#270] opened 2020-10-18 00:43 UTC
> There have also been several updates to various libraries, both in the graphics
> and input stacks, and several userland drivers have been updated.
> Libraries such as `libdrm` and `libevdev` which includes new FreeBSD support
> developed by team members and added upstream.

The second sentence in that paragraph seems to lack a main clause but I'm not sure what the fix is. Possible changes that came to mind are:
- s/which includes/include/ (second sentence) if that sentence is meant to stand on its own.
- Merge both sentences using : if the second sentence is actually meant to list the updated userland drivers and libevdev is the only one that includes new FreeBSD support.
- Merge both sentences using : and s/includes/include/ if the second sentence is actually meant to list the updated userland drivers and both libdrm and liibevdev include new FreeBSD support.

**Comment by debdrup** [comment] 2020-10-18 09:32
I've tried to address this in a way that makes sense to me with https://github.com/freebsd/freebsd-quarterly/commit/df89eff9cc31b3e4a837eec1d29aa63dbfec736d
Perhaps @zeising can give the okay for the wording, to ensure it's what was intended?

**Comment by debdrup** [comment] 2020-10-21 12:51
This has been fixed with https://github.com/freebsd/freebsd-quarterly/commit/44b4b99ad93f03ca54a65a5cb913fea2972c4d93

**Closed by debdrup** 2020-10-21 12:51 UTC
